language: android
jdk: oraclejdk8
android:
   components:
      - tools
      - platform-tools
      - build-tools-27.0.2
      - android-27
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
sudo: false
before_install:
  - nvm install 10.16.3
  - echo y | sdkmanager "ndk-bundle"
install:
  - npm install
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - sh scripts/travis_build.sh
  - cd android && ./gradlew build connectedCheck
  # - test -e platforms/android/app/build/outputs/apk/debug/app-debug.apk 
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.npm
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
