language: android
jdk: oraclejdk8
android:
   components:
      - tools
      - platform-tools
      - build-tools-27.0.2
      - android-27
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
sudo: false
before_install:
  - nvm install 12.2.0
  - echo y | sdkmanager "ndk-bundle"
install:
  - npm install
  # mandatory web build first (otherwise npx cap update will fail)
  - npm run build
  - npx cap update android
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - npm run lint
  - npm run test
  - cd android && ./gradlew assembleDebug
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.npm
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
