#
# Your Crowdin credentials
#
"project_id": ""
"api_token": ""
"base_path": "."
"base_url": "https://api.crowdin.com"
"commit_message": 'New translations: %original_file_name% (%language%)'
"append_commit_message": false

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/translation/source/*.json",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/translation/dest/%locale%/%file_name%.%file_extension%",

  #
  # File type
  # e.g. "json"
  #
  "type" : "json",

  #
  # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed strings will be removed. Use to fix typos and for minor changes in the source strings
  # e.g. "update_as_unapproved" or "update_without_changes"
  #
  "update_option" : "update_without_changes"
 }
]
