# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Android build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
    branches-ignore:
      - 'l10n_master'

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build web
        run: npm run build
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Sync android capacitor
        run: npx cap update android
      - name: Prepare build
        working-directory: ./node_modules/capacitor-stockfish/stockfish/src
        run: make net
      - name: Build APKs
        working-directory: ./android
        run: |
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        with:
          name: debugApk
          path: |
            ./android/app/build/outputs/apk/debug/
      - name: Patch nonfree
        env:
          PATCH_NONFREE_FORCE: "1"
        run: npm run patch-nonfree
      - name: Sync android capacitor
        run: npx cap update android
      - name: Build Free APKs
        working-directory: ./android
        run: ./gradlew assembleDebug
      - name: Check non-free dependencies
        working-directory: ./android/app/build/outputs/apk/debug/
        run: |
          dexdump=$(find $ANDROID_HOME/build-tools/ -name 'dexdump' | sort -r | head -1)
          ! $dexdump app-debug.apk | grep 'Class descriptor' | grep com\/google\/firebase
          ! $dexdump app-debug.apk | grep 'Class descriptor' | grep com\/google\/android\/gms
      - uses: actions/upload-artifact@v2
        with:
          name: freeDebugApk
          path: ./android/app/build/outputs/apk/debug/
