name: Android build

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/build.yml'

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
      - name: Build web
        run: npm run build
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Sync android capacitor
        run: npx cap update android
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Prepare build
        working-directory: ./node_modules/capacitor-stockfish/stockfish/src
        run: make net
      - name: Build APKs
        working-directory: ./android
        run: |
          ./gradlew assembleWithoutNNUEDebug
          ./gradlew assembleWithNNUEDebug
      - uses: actions/upload-artifact@v2
        with:
          name: debugApks
          path: |
            ./android/app/build/outputs/apk/withoutNNUE/debug/
            ./android/app/build/outputs/apk/withNNUE/debug/
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
